//
//  LevelGreek.h
//  History For Kids
//
//  Created by haythem on 4/9/15.
//  Copyright (c) 2015 Infinity Edge. All rights reserved.
//

#import <SpriteKit/SpriteKit.h>
#import "JSTileMap.h"
#import <AVFoundation/AVFoundation.h>

@interface LevelGreek : SKScene

@property BOOL contentCreated;
@property (nonatomic, strong) JSTileMap *mapGreek;
@property (nonatomic, strong) SKNode *myWorldView;
@property (nonatomic, strong) SKSpriteNode *alien;
@property (nonatomic, strong) SKSpriteNode *greekTrader;
@property (nonatomic, strong) SKSpriteNode *greekOfficer;
@property (nonatomic, strong) SKSpriteNode *greekPolitician;
@property (nonatomic, strong) SKSpriteNode *greekMarine;
@property (nonatomic, strong) SKSpriteNode *dialog;
@property (nonatomic, strong) SKAction *idleAnimation;
@property (nonatomic, strong) SKAction *walkAnimation;
@property (nonatomic, strong) SKAction *walk2Animation;
@property (nonatomic, strong) SKAction *traderAnimation;
@property (nonatomic, strong) SKAction *politicianAnimation;
@property (nonatomic, strong) SKAction *officerAnimation;
@property (nonatomic, strong) SKAction *marineAnimation;
@property (nonatomic, strong) SKSpriteNode *rightControl;
@property (nonatomic, strong) SKSpriteNode *leftControl;
@property (nonatomic, strong) SKSpriteNode *SelectControl;
@property  NSTimeInterval touchTime;
@property  NSTimeInterval elapsedTime;
@property  NSTimeInterval deltaTime;
@property  NSTimeInterval countTime;
@property BOOL isMovingLeft;
@property BOOL isMovingRight;
@property BOOL greekCleared1;
@property BOOL greekCleared2;
@property BOOL greekCleared3;
@property BOOL greekCleared4;
@property BOOL greekSpeech11;
@property BOOL greekSpeech12;
@property BOOL greekSpeech13;
@property BOOL greekSpeech21;
@property BOOL greekSpeech22;
@property BOOL greekSpeech23;
@property BOOL greekSpeech31;
@property BOOL greekSpeech32;
@property BOOL greekSpeech33;
@property BOOL greekSpeech41;
@property BOOL greekSpeech42;
@property BOOL greekSpeech43;
@property BOOL greekquiz11;
@property BOOL greekquiz12;
@property BOOL greekquiz13;
@property BOOL greekquiz21;
@property BOOL greekquiz22;
@property BOOL greekquiz23;
@property BOOL greekquiz31;
@property BOOL greekquiz32;
@property BOOL greekquiz33;
@property BOOL greekquiz41;
@property BOOL greekquiz42;
@property BOOL greekquiz43;
@property BOOL skip;
@property (nonatomic, strong) SKSpriteNode *panel;
@property (nonatomic, strong) SKSpriteNode *backControl;
@property (nonatomic, strong) SKSpriteNode *answer111;
@property (nonatomic, strong) SKSpriteNode *answer112;
@property (nonatomic, strong) SKSpriteNode *answer113;
@property (nonatomic, strong) SKSpriteNode *answer121;
@property (nonatomic, strong) SKSpriteNode *answer122;
@property (nonatomic, strong) SKSpriteNode *answer123;
@property (nonatomic, strong) SKSpriteNode *answer131;
@property (nonatomic, strong) SKSpriteNode *answer132;
@property (nonatomic, strong) SKSpriteNode *answer133;
@property (nonatomic, strong) SKSpriteNode *answer211;
@property (nonatomic, strong) SKSpriteNode *answer212;
@property (nonatomic, strong) SKSpriteNode *answer213;
@property (nonatomic, strong) SKSpriteNode *answer221;
@property (nonatomic, strong) SKSpriteNode *answer222;
@property (nonatomic, strong) SKSpriteNode *answer223;
@property (nonatomic, strong) SKSpriteNode *answer231;
@property (nonatomic, strong) SKSpriteNode *answer232;
@property (nonatomic, strong) SKSpriteNode *answer233;
@property (nonatomic, strong) SKSpriteNode *answer311;
@property (nonatomic, strong) SKSpriteNode *answer312;
@property (nonatomic, strong) SKSpriteNode *answer313;
@property (nonatomic, strong) SKSpriteNode *answer321;
@property (nonatomic, strong) SKSpriteNode *answer322;
@property (nonatomic, strong) SKSpriteNode *answer323;
@property (nonatomic, strong) SKSpriteNode *answer331;
@property (nonatomic, strong) SKSpriteNode *answer332;
@property (nonatomic, strong) SKSpriteNode *answer333;
@property (nonatomic, strong) SKSpriteNode *answer411;
@property (nonatomic, strong) SKSpriteNode *answer412;
@property (nonatomic, strong) SKSpriteNode *answer413;
@property (nonatomic, strong) SKSpriteNode *answer421;
@property (nonatomic, strong) SKSpriteNode *answer422;
@property (nonatomic, strong) SKSpriteNode *answer423;
@property (nonatomic, strong) SKSpriteNode *answer431;
@property (nonatomic, strong) SKSpriteNode *answer432;
@property (nonatomic, strong) SKSpriteNode *answer433;
@property (nonatomic, strong) SKLabelNode *speech111;
@property (nonatomic, strong) SKLabelNode *speech112;
@property (nonatomic, strong) SKLabelNode *speech113;
@property (nonatomic, strong) SKLabelNode *speech114;
@property (nonatomic, strong) SKLabelNode *speech115;
@property (nonatomic, strong) SKLabelNode *speech121;
@property (nonatomic, strong) SKLabelNode *speech122;
@property (nonatomic, strong) SKLabelNode *speech123;
@property (nonatomic, strong) SKLabelNode *speech124;
@property (nonatomic, strong) SKLabelNode *speech125;
@property (nonatomic, strong) SKLabelNode *speech131;
@property (nonatomic, strong) SKLabelNode *speech132;
@property (nonatomic, strong) SKLabelNode *speech133;
@property (nonatomic, strong) SKLabelNode *speech134;
@property (nonatomic, strong) SKLabelNode *speech135;
@property (nonatomic, strong) SKLabelNode *quiz111;
@property (nonatomic, strong) SKLabelNode *quiz112;
@property (nonatomic, strong) SKLabelNode *quiz113;
@property (nonatomic, strong) SKLabelNode *quiz114;
@property (nonatomic, strong) SKLabelNode *quiz121;
@property (nonatomic, strong) SKLabelNode *quiz122;
@property (nonatomic, strong) SKLabelNode *quiz123;
@property (nonatomic, strong) SKLabelNode *quiz124;
@property (nonatomic, strong) SKLabelNode *quiz131;
@property (nonatomic, strong) SKLabelNode *quiz132;
@property (nonatomic, strong) SKLabelNode *quiz133;
@property (nonatomic, strong) SKLabelNode *quiz134;
@property (nonatomic, strong) SKLabelNode *speech211;
@property (nonatomic, strong) SKLabelNode *speech212;
@property (nonatomic, strong) SKLabelNode *speech213;
@property (nonatomic, strong) SKLabelNode *speech214;
@property (nonatomic, strong) SKLabelNode *speech215;
@property (nonatomic, strong) SKLabelNode *speech221;
@property (nonatomic, strong) SKLabelNode *speech222;
@property (nonatomic, strong) SKLabelNode *speech223;
@property (nonatomic, strong) SKLabelNode *speech224;
@property (nonatomic, strong) SKLabelNode *speech225;
@property (nonatomic, strong) SKLabelNode *speech231;
@property (nonatomic, strong) SKLabelNode *speech232;
@property (nonatomic, strong) SKLabelNode *speech233;
@property (nonatomic, strong) SKLabelNode *speech234;
@property (nonatomic, strong) SKLabelNode *speech235;
@property (nonatomic, strong) SKLabelNode *quiz211;
@property (nonatomic, strong) SKLabelNode *quiz212;
@property (nonatomic, strong) SKLabelNode *quiz213;
@property (nonatomic, strong) SKLabelNode *quiz214;
@property (nonatomic, strong) SKLabelNode *quiz221;
@property (nonatomic, strong) SKLabelNode *quiz222;
@property (nonatomic, strong) SKLabelNode *quiz223;
@property (nonatomic, strong) SKLabelNode *quiz224;
@property (nonatomic, strong) SKLabelNode *quiz231;
@property (nonatomic, strong) SKLabelNode *quiz232;
@property (nonatomic, strong) SKLabelNode *quiz233;
@property (nonatomic, strong) SKLabelNode *quiz234;
@property (nonatomic, strong) SKLabelNode *speech311;
@property (nonatomic, strong) SKLabelNode *speech312;
@property (nonatomic, strong) SKLabelNode *speech313;
@property (nonatomic, strong) SKLabelNode *speech314;
@property (nonatomic, strong) SKLabelNode *speech315;
@property (nonatomic, strong) SKLabelNode *speech321;
@property (nonatomic, strong) SKLabelNode *speech322;
@property (nonatomic, strong) SKLabelNode *speech323;
@property (nonatomic, strong) SKLabelNode *speech324;
@property (nonatomic, strong) SKLabelNode *speech325;
@property (nonatomic, strong) SKLabelNode *speech331;
@property (nonatomic, strong) SKLabelNode *speech332;
@property (nonatomic, strong) SKLabelNode *speech333;
@property (nonatomic, strong) SKLabelNode *speech334;
@property (nonatomic, strong) SKLabelNode *speech335;
@property (nonatomic, strong) SKLabelNode *quiz311;
@property (nonatomic, strong) SKLabelNode *quiz312;
@property (nonatomic, strong) SKLabelNode *quiz313;
@property (nonatomic, strong) SKLabelNode *quiz314;
@property (nonatomic, strong) SKLabelNode *quiz321;
@property (nonatomic, strong) SKLabelNode *quiz322;
@property (nonatomic, strong) SKLabelNode *quiz323;
@property (nonatomic, strong) SKLabelNode *quiz324;
@property (nonatomic, strong) SKLabelNode *quiz331;
@property (nonatomic, strong) SKLabelNode *quiz332;
@property (nonatomic, strong) SKLabelNode *quiz333;
@property (nonatomic, strong) SKLabelNode *quiz334;
@property (nonatomic, strong) SKLabelNode *speech411;
@property (nonatomic, strong) SKLabelNode *speech412;
@property (nonatomic, strong) SKLabelNode *speech413;
@property (nonatomic, strong) SKLabelNode *speech414;
@property (nonatomic, strong) SKLabelNode *speech415;
@property (nonatomic, strong) SKLabelNode *speech421;
@property (nonatomic, strong) SKLabelNode *speech422;
@property (nonatomic, strong) SKLabelNode *speech423;
@property (nonatomic, strong) SKLabelNode *speech424;
@property (nonatomic, strong) SKLabelNode *speech425;
@property (nonatomic, strong) SKLabelNode *speech431;
@property (nonatomic, strong) SKLabelNode *speech432;
@property (nonatomic, strong) SKLabelNode *speech433;
@property (nonatomic, strong) SKLabelNode *speech434;
@property (nonatomic, strong) SKLabelNode *speech435;
@property (nonatomic, strong) SKLabelNode *quiz411;
@property (nonatomic, strong) SKLabelNode *quiz412;
@property (nonatomic, strong) SKLabelNode *quiz413;
@property (nonatomic, strong) SKLabelNode *quiz414;
@property (nonatomic, strong) SKLabelNode *quiz421;
@property (nonatomic, strong) SKLabelNode *quiz422;
@property (nonatomic, strong) SKLabelNode *quiz423;
@property (nonatomic, strong) SKLabelNode *quiz424;
@property (nonatomic, strong) SKLabelNode *quiz431;
@property (nonatomic, strong) SKLabelNode *quiz432;
@property (nonatomic, strong) SKLabelNode *quiz433;
@property (nonatomic, strong) SKLabelNode *quiz434;
@property (nonatomic, strong) AVAudioPlayer *backgroundAudioPlayer;
@property  CGPoint deltaPosition;



@end
